### ISSUE TITLE
[INSTALL]: Spack-Stacks under Hera-Rocky8

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [JCSDA/spack-stack#1005]
### Package name

unified-env and gsi-addon environments

### Package version/tag

1.5.1 and 1.6.0 (and some)

### Build options

Build with /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env-rocky8/install as the upstream.

### Installation timeframe

Needed before the final transition to Rocky 8 in April for testing.  It's OK if the test directory needs to end up somewhere else.

### Checklist:
- [x] spack-stack-1.3.0/unified-env (@RatkoVasic-NOAA)
 /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.3.0/envs/unified-env-rocky8/install/modulefiles/Core
- [x] spack-stack-1.3.1/unified-env (@RatkoVasic-NOAA)
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.3.1/envs/unified-env-rocky8/install/modulefiles/Core
- [x] spack-stack-1.4.1/unified-env (@RatkoVasic-NOAA)
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.4.1/envs/unified-env-rocky8/install/modulefiles/Core
- [x] spack-stack-1.5.0/unified-env (@RatkoVasic-NOAA)
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.0/envs/unified-env-rocky8/install/modulefiles/Core
- [x] spack-stack-1.5.1/unified-env-rocky8 (@AlexanderRichert-NOAA)
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env-rocky8/install/modulefiles/Core
- [x] spack-stack-1.5.1/gsi-addon-env-rocky8 (@AlexanderRichert-NOAA)
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/gsi-addon-env-rocky8/install/modulefiles/Core
- [x] spack-stack-1.6.0/unified-env-rocky8 (@RatkoVasic-NOAA )
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/modulefiles/Core
- [x] spack-stack-1.6.0/gsi-addon-env-rocky8 (@RatkoVasic-NOAA )
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev-rocky8/install/modulefiles/Core

**Comment by AlexanderRichert-NOAA** [comment]
@RatkoVasic-NOAA @climbfuji @ulmononian let's use this issue for coordinating Hera rebuilds.

**Comment by RatkoVasic-NOAA** [comment]
I added all envs already existing on Hera in checklist. But I'm pretty sure not all are in use. Can someone here confirm which installations are NOT needed?

**Comment by DavidHuber-NOAA** [comment]
The gsi-addon environment for v1.6.0 (/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev-rocky8) does not include a module file for crtm/2.4.0.1.  Is it possible that upstream modules haven't yet been incorporated into this installation?  (i.e. `spack module lmod refresh --upstream-modules`)

**Comment by RatkoVasic-NOAA** [comment]
@DavidHuber-NOAA I ran spack module lmod refresh --upstream-modules, can you check if it  is OK now?

**Comment by DavidHuber-NOAA** [comment]
Yes, thanks @RatkoVasic-NOAA!

**Comment by climbfuji** [comment]
All the boxes in the checklist above are ticked, can we close this issue as completed?

**Comment by RatkoVasic-NOAA** [comment]
> All the boxes in the checklist above are ticked, can we close this issue as completed?

Yes, I tested SRW and UFS-WM using new OS.

**Comment by DavidHuber-NOAA** [comment]
It looks like a couple other modules, for esmf and mapl, are missing from gsi-addon-dev-rocky8:

```console
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev/install/modulefiles/intel-oneapi-mpi/2021.5.1/intel/2021.5.0/esmf/:
8.6.0.lua
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev/install/modulefiles/intel-oneapi-mpi/2021.5.1/intel/2021.5.0/mapl/:
2.40.3-esmf-8.6.0.lua

/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev-rocky8/install/modulefiles/intel-oneapi-mpi/2021.5.1/intel/2021.5.0/esmf/:
8.5.0.lua
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev-rocky8/install/modulefiles/intel-oneapi-mpi/2021.5.1/intel/2021.5.0/mapl/:
2.40.3-esmf-8.5.0.lua
```

I don't think that these are necessary for the global workflow, so I'm just making a note of this.

**Comment by climbfuji** [comment]
These modules will only be created if the packages are requested in gsi-addon-dev. Do you know if they are?

**Comment by DavidHuber-NOAA** [comment]
Not exactly, no.  The gsi-addon-dev template uses the `unified-weather-model-env` package which has a dependency on esmf.  The upstream unified-dev template is where esmf versions are specified, both 8.5.0 and 8.6.0.  So it seems that with Rocky8, the gsi-addon build captured 8.5.0 while CentOS captured 8.6.0.

I still don't think any action is needed here, but it is something worth noting as reproducibility is important for spack-stack.  If we need to develop another downstream environment, we should be careful and deliberate about inheriting the correct version of an upstream library in cases where 2 or more exist.  Again, esmf is not a necessary library for gsi-addon-dev, so it's not presently an issue.

**Comment by climbfuji** [comment]
This problem will likely go away with 1.7.0, since we will only have one version of these packages. But, for future reference, for releases that have two or more esmf/mapl combinations, you'll need to specify which ones you want for ufs-weather-model-env, like so:
```
- ufs-weather-model-env ^mapl@x.y.z ^esmf@x.y.z
```
Essentially the same as in the unified-dev template for those releases (e.g. https://github.com/JCSDA/spack-stack/blob/0c2ff3b5c61f5e0d78d08ca7392dd4de4c915bf5/configs/templates/unified-dev/spack.yaml#L25).
