### ISSUE TITLE
[INSTALL]: Spack-Stacks under Jet-Rocky8

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [JCSDA/spack-stack#1010]
### Package name

spack-stack

### Package version/tag

1.6.0, 1.5.1, 1.5.0

### Installation timeframe

Sometime in March Jet will transition completely to Rocky OS. Starting today (2/21/2024) we have access to both Rocky and CentOS.

### Checklist

- [x] spack-stack-1.5.0/envs/unified-env (@RatkoVasic-NOAA)
- [x] spack-stack-1.5.1/envs/gsi-addon (@RatkoVasic-NOAA)
- [x] spack-stack-1.5.1/envs/unified-env (@RatkoVasic-NOAA)
- [x] spack-stack-1.6.0/envs/gsi-addon-dev (@RatkoVasic-NOAA)
- [x] spack-stack-1.6.0/envs/unified-env (@RatkoVasic-NOAA)

**Comment by climbfuji** [comment]
All the boxes above are ticked, ok to close?

**Comment by RatkoVasic-NOAA** [comment]
> All the boxes above are ticked, ok to close?

Yes, I tested both SRW and WM using new OS on Jet.
