### ISSUE TITLE
[INSTALL]: Use Python 3.11 for unified-environment

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1038]
### Package name

python

### Package version/tag

3.11

### Build options

current

### Installation timeframe

Target release: spack-stack-1.8.0 around June/July 2024

This update was requested by NOAA and EPIC and is certainly the right thing to do

### Other information

This will need thorough testing and probably some development in applications

### WCOSS2

- [X] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: General questions

Python is already approved on WCOSS2 and an integral part of all applications. The roll-out of spack-stack-1.8.0 on wcoss2 doesn't have to happen immediately (=at the same time as on the other HPCs), but hopefully by the time NCO has approved the use of spack-stack (or spack standalone) on WCOSS2, they'll be able to accommodate this update.

I am not filling in the wcoss2 check boxes below, because (a) Python 3 is already approved on the system, and (b) I think EMC will be in a better position to answer those questions.

### WCOSS2: Installation and testing

n/a

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

**Comment by eap** [comment]
@eap - this needs to also be tracked in isues with repository based owners for all of our owned python code... can some of these checks be automated with static analysis?

Affected repos: r2d2 client, r2d2 main (until migrate to server), ewok, solo, skylab, simobs, ioda-converters, ioda
