### ISSUE TITLE
spack-stack 1.7.0 testing

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#1042]
This is a tracking issue for testing release/1.7.0.

For now, to test out the shortened naming schemes, let's use, e.g., ue-intel, ue-gcc, etc. (and remember to install a separate stack for each compiler).

Systems:
- [x] Hercules (@RatkoVasic-NOAA)
/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.7.0/envs/ (gsi-addon-gcc  gsi-addon-intel  ue-gcc  ue-intel)
- [x] Orion (@RatkoVasic-NOAA) 
- [x] Discover (@climbfuji and @srherbener)
- [x] Casper (@climbfuji)
- [x] Derecho (@RatkoVasic-NOAA) 
/glade/work/epicufsrt/contrib/spack-stack/derecho/spack-stack-1.7.0/envs (ue-gcc  ue-intel)
- [x] Acorn (@AlexanderRichert-NOAA; /lfs/h1/emc/nceplibs/noscrub/spack-stack/spack-stack-1.7.0/envs/ue-intel{19,2022})
- [x] Gaea C5 (@RatkoVasic-NOAA)
/ncrc/proj/epic/spack-stack/spack-stack-1.7.0/envs (gsi-addon-intel  ue-intel)
- [x] Hera (@AlexanderRichert-NOAA; /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.7.0/envs/{ue,gsi-addon}-{intel,gcc}; ran a couple of UFS test builds)
- [x] Jet (@AlexanderRichert-NOAA;  /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.7.0/envs/{ue,gsi-addon}-{intel,gcc})
- [x] Narwhal (@climbfuji)
- [x] Nautilus (@climbfuji)
- [x] S4 (@climbfuji and @ashley314)
- [x] AWS AMI RH 8 (@climbfuji)
- [x] AWS CI cluster (existing, c6i; @climbfuji)
- [ ] ~~AWS ParallelCluster~~ (decommissioned - if resurrected, then @climbfuji)
- [x] NOAA ParallelWorks EPIC (@natalie-perlin) 
AWS, GCP, Azure: /contrib/spack-stack/spack-stack/1.7.0/envs/ue-intel
NB: Azure built a spack-stack directly in common space, launching "spack install" twice.
- [x] NOAA ParallelWorks JCSDA (@climbfuji)

Issues encountered:
 - RESOLVED: Hera needs zlib-ng to be static only. I have added the necessary config changes (incl. update to compiler OS and external OpenMPI module/version).
 - Note on UFS Weather Model: If testing against UFS Weather Model, note that a handful of changes are needed on account of ip@5. Message me or run a `git diff` in /scratch1/NCEPDEV/nems/Alexander.Richert/ufs-weather-model to see the changes needed (basically, `sp` becomes `ip` in all the CMakeLists.txt's, plus a no-openmp flag needs to be explicitly set in FV3/ccpp/physics/CMakeLists.txt.
 - RESOLVED: On Jet, py-nodeenv and awscli-v2 were failing to build because they can't load `ssl_` from urllib3. Resolved by using gcc/9.2.0b. 
 - Note: grib-util 1.4.0 won't build with older Intel compilers that lack F2018 standard support. If this is a problem anywhere other than Acorn, then let's implement a patch. For now this is fixed manually on Acorn, and will be fixed in the next version.
 - Note: To get odc to compile on Acorn, I had to patch the root CMakeLists.txt to use c++17 instead of c++11. Not sure why this isn't an issue on other systems.
 - RESOLVED: Hera: Running out of space for gsi-addon builds. EPIC has cleared out some space (thank you!).
 - RESOLVED: Jet: HDF5 failing to build with gcc due to using the centos7 gcc. Jet site config has been updated locally, permanent updates will be pushed shortly.

**Comment by RatkoVasic-NOAA** [comment]
I suggest we do the Orion in a month. It is switching from CentOS to Rocky OS on Apr 24th.

**Comment by natalie-perlin** [comment]
Cloud platforms (NOAA Parallel Works) may take longer to put into team plans, need to leave for April. Rocky8 is now available on the cloud platforms, so two sets of stacks may now be built, one for Centos 7 and another for Rocky8.

**Comment by climbfuji** [comment]
> Cloud platforms (NOAA Parallel Works) may take longer to put into team plans, need to leave for April. Rocky8 is now available on the cloud platforms, so two sets of stacks may now be built, one for Centos 7 and another for Rocky8.

I'll do the JCSDA ParallelWorks Gcloud build immediately, since we are using the system actively at the moment.

**Comment by climbfuji** [comment]
I've updated the list and added my name in various places

**Comment by natalie-perlin** [comment]
@climbfuji - AWS and GCP have been successfully built on NOAA ParallelWorks, under /contrib/spack-stack/spack-stack1.7.0 . Initially built as ./envs/unified-env, and now being re-built as ./envs/ue-intel/

Azure: mirror spack-stack-1.7.0 built has been started on a local instance, as a serial job under /lustre/. When finished, will then be rebuilt from the mirror in a common space under /contrib/spack-stack/.

**Comment by srherbener** [comment]
I have built and tested jedi-bundle on Discover, SCU16 with both gnu/openmpi and intel/oneapi-mpi. Both builds succeeded, and all jedi-bundles tests pass on GNU. However, I'm seeing the following test failures on Intel:
```
The following tests FAILED:
        408 - saber_test_process_perts_from_csdual_states_2_1-1 (Failed)
        530 - saber_test_process_perts_from_csdual_states_2_2-1 (Failed)
        1538 - ufo_test_tier1_test_ufo_qc_historycheck (Failed)
        1539 - ufo_test_tier1_test_ufo_qc_historycheck_mpi (Failed)
        1540 - ufo_test_tier1_test_ufo_qc_historycheck_unittests (Failed)
        1573 - ufo_test_tier1_test_ufo_qc_variableassignment (Failed)
        2414 - test_soca_forecast_pseudo (Failed)
        2423 - test_soca_parameters_diffusion (Failed)
        2424 - test_soca_enspert (Failed)
        2430 - test_soca_sqrtvertloc (Failed)
        2433 - test_soca_dirac_soca_cov (Failed)
        2434 - test_soca_dirac_socahyb_cov (Failed)
        2435 - test_soca_dirac_diffusion (Failed)
        2438 - test_soca_hofx_4d_pseudo (Failed)
        2439 - test_soca_3dvar (Failed)
        2441 - test_soca_3dvarfgat_pseudo (Failed)
        2442 - test_soca_3dhyb (Failed)
        2443 - test_soca_3dhyb_diffusion (Failed)
        2444 - test_soca_3dhybfgat_pseudo (Failed)
        2445 - test_soca_4denvar (Failed)
        2446 - test_soca_4dhybenvar (Failed)
        2450 - test_soca_addincrement (Failed)
        2451 - test_soca_convertincrement (Failed)
        2500 - test_mpasjedi_lgetkf_height_vloc (Failed)
```

The saber test failures are due to floating point tolerance being missed in comparisons made after the application successfully fiinishe.

The UFO test failures are crashes and exceptions not being caught by the test setup. It looks like these might be related to accessing netcdf/hdf5 files, but not sure.

The SOCA test failures are due to tolerance in floating point comparisons, floating point exceptoins and crashes due to not being able to find restart files

The MPAS test failure is due to tolerance of floating point comparisons.

Do these test failures look familiar? Is there a chance I did something wrong with the intel build? I'm asking because these tests passed with GNU/OpenMPI.

Thanks!

**Comment by climbfuji** [comment]
Did you also try to set up skylab, i.e. install the workflow dependencies?

**Comment by srherbener** [comment]
Yes, and I tried creating an experiment with my GNU/OpenMPI environment. I go this error from create_experiment.py:
```
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
```

**Comment by srherbener** [comment]
Another note: for my successful GNU/OpenMP and Intel/oneapi-mpi builds I had gsibec and sp loaded.

**Comment by natalie-perlin** [comment]
Building a mirror on NOAA Azure: 
mirror seems to be built successfully under /lustre, and is staged now under
`/contrib/spack-stack/spackmirror170`.
 Getting an error when running the boostrap step:
 
``` 
[ue-intel] [root@NOAA-AZ:/contrib/spack-stack/spack-stack-1.7.0/envs/ue-intel]# spack bootstrap mirror --binary-packages /contrib/spack-stack/spackmirror170
==> Adding "clingo-bootstrap@spack+python %gcc target=x86_64" and dependencies to the mirror at /contrib/spack-stack/spackmirror170/bootstrap_cache
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    clingo-bootstrap@spack%gcc+python arch=None-None-x86_64 is unsatisfiable
```

**Comment by climbfuji** [comment]
> Building a mirror on NOAA Azure: mirror seems to be built successfully under /lustre, and is staged now under `/contrib/spack-stack/spackmirror170`. Getting an error when running the boostrap step:
> 
> ```
> [ue-intel] [root@NOAA-AZ:/contrib/spack-stack/spack-stack-1.7.0/envs/ue-intel]# spack bootstrap mirror --binary-packages /contrib/spack-stack/spackmirror170
> ==> Adding "clingo-bootstrap@spack+python %gcc target=x86_64" and dependencies to the mirror at /contrib/spack-stack/spackmirror170/bootstrap_cache
> ==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
>     clingo-bootstrap@spack%gcc+python arch=None-None-x86_64 is unsatisfiable
> ```

We don't usually run this step, why is it needed?

**Comment by climbfuji** [comment]
> I have built and tested jedi-bundle on Discover, SCU16 with both gnu/openmpi and intel/oneapi-mpi. Both builds succeeded, and all jedi-bundles tests pass on GNU. However, I'm seeing the following test failures on Intel:
> 
> ```
> The following tests FAILED:
>         408 - saber_test_process_perts_from_csdual_states_2_1-1 (Failed)
>         530 - saber_test_process_perts_from_csdual_states_2_2-1 (Failed)
>         1538 - ufo_test_tier1_test_ufo_qc_historycheck (Failed)
>         1539 - ufo_test_tier1_test_ufo_qc_historycheck_mpi (Failed)
>         1540 - ufo_test_tier1_test_ufo_qc_historycheck_unittests (Failed)
>         1573 - ufo_test_tier1_test_ufo_qc_variableassignment (Failed)
>         2414 - test_soca_forecast_pseudo (Failed)
>         2423 - test_soca_parameters_diffusion (Failed)
>         2424 - test_soca_enspert (Failed)
>         2430 - test_soca_sqrtvertloc (Failed)
>         2433 - test_soca_dirac_soca_cov (Failed)
>         2434 - test_soca_dirac_socahyb_cov (Failed)
>         2435 - test_soca_dirac_diffusion (Failed)
>         2438 - test_soca_hofx_4d_pseudo (Failed)
>         2439 - test_soca_3dvar (Failed)
>         2441 - test_soca_3dvarfgat_pseudo (Failed)
>         2442 - test_soca_3dhyb (Failed)
>         2443 - test_soca_3dhyb_diffusion (Failed)
>         2444 - test_soca_3dhybfgat_pseudo (Failed)
>         2445 - test_soca_4denvar (Failed)
>         2446 - test_soca_4dhybenvar (Failed)
>         2450 - test_soca_addincrement (Failed)
>         2451 - test_soca_convertincrement (Failed)
>         2500 - test_mpasjedi_lgetkf_height_vloc (Failed)
> ```
> 
> The saber test failures are due to floating point tolerance being missed in comparisons made after the application successfully fiinishe.
> 
> The UFO test failures are crashes and exceptions not being caught by the test setup. It looks like these might be related to accessing netcdf/hdf5 files, but not sure.
> 
> The SOCA test failures are due to tolerance in floating point comparisons, floating point exceptoins and crashes due to not being able to find restart files
> 
> The MPAS test failure is due to tolerance of floating point comparisons.
> 
> Do these test failures look familiar? Is there a chance I did something wrong with the intel build? I'm asking because these tests passed with GNU/OpenMPI.
> 
> Thanks!

These tests fail on S4 with Intel. Same as yours except my gsibec failures. These could be because I didn't unload the `gsibec` module but still built it in the bundle
```
	  1 - gsibec_test_tier1_geos (Failed)
	  2 - gsibec_test_tier1_gfs (Failed)
	1541 - ufo_test_tier1_test_ufo_qc_historycheck (Failed)
	1542 - ufo_test_tier1_test_ufo_qc_historycheck_mpi (Failed)
	1543 - ufo_test_tier1_test_ufo_qc_historycheck_unittests (Failed)
	1576 - ufo_test_tier1_test_ufo_qc_variableassignment (Failed)
	2269 - test_femps_csgrid (Failed)
	2415 - test_soca_forecast_pseudo (Failed)
	2424 - test_soca_parameters_diffusion (Failed)
	2425 - test_soca_enspert (Failed)
	2431 - test_soca_sqrtvertloc (Failed)
	2434 - test_soca_dirac_soca_cov (Failed)
	2435 - test_soca_dirac_socahyb_cov (Failed)
	2436 - test_soca_dirac_diffusion (Failed)
	2439 - test_soca_hofx_4d_pseudo (Failed)
	2440 - test_soca_3dvar (Failed)
	2442 - test_soca_3dvarfgat_pseudo (Failed)
	2443 - test_soca_3dhyb (Failed)
	2444 - test_soca_3dhyb_diffusion (Failed)
	2445 - test_soca_3dhybfgat_pseudo (Failed)
	2446 - test_soca_4denvar (Failed)
	2447 - test_soca_4dhybenvar (Failed)
	2451 - test_soca_addincrement (Failed)
	2452 - test_soca_convertincrement (Failed)
	2501 - test_mpasjedi_lgetkf_height_vloc (Failed)
```

**Comment by natalie-perlin** [comment]
> > Building a mirror on NOAA Azure: mirror seems to be built successfully under /lustre, and is staged now under `/contrib/spack-stack/spackmirror170`. Getting an error when running the boostrap step:
> > ```
> > [ue-intel] [root@NOAA-AZ:/contrib/spack-stack/spack-stack-1.7.0/envs/ue-intel]# spack bootstrap mirror --binary-packages /contrib/spack-stack/spackmirror170
> > ==> Adding "clingo-bootstrap@spack+python %gcc target=x86_64" and dependencies to the mirror at /contrib/spack-stack/spackmirror170/bootstrap_cache
> > ==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
> >     clingo-bootstrap@spack%gcc+python arch=None-None-x86_64 is unsatisfiable
> > ```
> 
> We don't usually run this step, why is it needed?

This appeared to be an essential step for the spack-stack to be built from the mirror. If the bootstrap fails reporting a concretizer errors (`spack bootstrap mirror --binary-packages /contrib/spack-stack/spackmirror170`), the subsequent steps fail as well. The subsequent steps are supposed to be the following:

```
cd /contrib/spack-stack/spack-stack-1.7.0/envs/ue-intel
spack mirror add local-binary file:///contrib/spack-stack/spackmirror170
spack mirror add local-source file:///contrib/spack-stack/spackmirror170
spack mirror list
spack concretize 2>&1 | tee log.concretize.ue-intel.001
#
spack buildcache update-index local-binary
spack buildcache list --allarch

spack install --cache-only --verbose --no-check-signature 2>&1 | tee log.install.ue-intel.001
```

What eventually worked out to build a spack-stack-1.7.0 successfully on NOAA Azure was the usual approach to build it in a common space as well, by running it twice. The first installation round did not complete successfully, but the second did. All is installed, modules generated successfully.

**Comment by climbfuji** [comment]
Closed via https://github.com/JCSDA/spack-stack/pull/1052
