### ISSUE TITLE
[INSTALL]: mapl@2.46.2 with esmf@8.6.1 (spack-stack-1.8.0)

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1062]
### Package name

mapl / esmf

### Package version/tag

2.45 / 8.6.1

### Build options

current - check if any changes

### Installation timeframe

For spack-stack-1.8.0

### Other information

- ESMF will have the bug fixes for the cmake target (`-lESMF` - `-lesmf`)
- mapl will have `gcc@13` support

### WCOSS2

- [X] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: General questions

current

### WCOSS2: Installation and testing

current

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

### WCOSS2: Additional comments

Both packages approved on wcoss2

**Comment by ulmononian** [comment]
@climbfuji is `esmf/8.6.1` available in spack yet? i didn't see it in https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/esmf/package.py or https://github.com/JCSDA/spack/blob/4fafe3eadbe330e64423b8ee16c88f8309f48d5b/var/spack/repos/builtin/packages/esmf/package.py. (@RatkoVasic-NOAA fyi, in regard to https://github.com/ufs-community/ufs-weather-model/issues/2230).

**Comment by climbfuji** [comment]
no, they are not yet available but should be soon

**Comment by jkbk2004** [comment]
@climbfuji if lib beta tags are listed, the package list may get too long. Is there a way to manually force the installation with static code release tag?

**Comment by climbfuji** [comment]
> @climbfuji if lib beta tags are listed, the package list may get too long. Is there a way to manually force the installation with static code release tag?

Sorry I don't understand what you are asking?

**Comment by jkbk2004** [comment]
> > @climbfuji if lib beta tags are listed, the package list may get too long. Is there a way to manually force the installation with static code release tag?
> 
> Sorry I don't understand what you are asking?

I mean there could be many alpha and beta tags released. I mean not necessary to list all those tags in the spack package list. Is there a way to just pull out beta tags and install? There are requests to test whenever beta tags are available: ESMF, FMS, MAPL.

**Comment by climbfuji** [comment]
Yes, that's possible. We won't install these in the official envs, or at least we would like to try to avoid that. We can do chained environments or other form of test installs on individual systems. Some of this is written down in the spack project charter, and we can certainly talk and make decisions on a case-by-case basis.

**Comment by ulmononian** [comment]
@RatkoVasic-NOAA can you try to add `esmf/8.6.1` to a chained env on 1.6.0 on hera? the mod can go into https://github.com/JCSDA/spack/blob/595a31bd0bb05a7e2017facc41552722919a8aaa/var/spack/repos/builtin/packages/esmf/package.py. the request on the wm side was for https://github.com/esmf-org/esmf/releases/tag/v8.6.1b03.

**Comment by mathomp4** [comment]
Note: I recommend 8.6.1b04 if you are going to pull a snapshot. It had a bug fix for some config file issues we found in GEOS.

I've been waiting to release MAPL 2.45 when 8.6.1 official was out (see https://github.com/GEOS-ESM/MAPL/pull/2682), but if need be, I can release it and then 8.6.1b04 will work. Just hoping to avoid ESMF beta snaps in the spack file :)

**Comment by RatkoVasic-NOAA** [comment]
@mathomp4 we installed esmf@8.6.1b04 on Hercules as chain environment under spack-stack-1.6.0
For WM we used combination, esmf@8.6.1b04 and mapl@2.40.3-esmf-8.6.0 (since mapl couldn't compile with esmf@8.6.1b04).
All tests passed OK. So, no need to hurry with mapl@2.45, which I understand, will work with esmf@8.6.1 version.

**Comment by mathomp4** [comment]
@RatkoVasic-NOAA Hmm. Do you mean spack wouldn't compile MAPL with ESMF 8.6.1? If so, then it's probably due to the different FindESMF.cmake package that moves to use `ESMF::ESMF` as the default target.

**Comment by RatkoVasic-NOAA** [comment]
@mathomp4 can you please look into Hercules, /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/ue-esmf861
There might be something that I missed in some *.yaml files?

**Comment by mathomp4** [comment]
@RatkoVasic-NOAA I don't have a Hercules account, unfortunately.

**Comment by mathomp4** [comment]
All, I talked with Tom today and we will probably make the "requires ESMF 8.6.1" version of MAPL, v2.46. v2.45 will be everything in our current `develop` up to that, we'll tag, and then we'll update the ESMF requirement in its own release. Just as a "separation of concerns".

I'm currently working on testing, etc. so hopefully we can soon get this in.

**Comment by mathomp4** [comment]
MAPL 2.46.2 is probably the best for this now. It is in mainline spack.
