### ISSUE TITLE
Move spack-stack to contrib on several systems

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#1156]
Developers have requested that spack-stack be deployed in common, NFS-based "contrib" systems to ensure stability.

Directories have been created on Hera and Jet. Let's start by doing a test deployment of whatever version in each space. If all goes well, then depending on developer needs we can re-deploy some past versions in those spaces, and do future deployments there.

- [x] Hera - test installing current develop branch and run with UFS WM (@AlexanderRichert-NOAA)
- [x] Jet - test installing current develop branch and run with UFS WM (@AlexanderRichert-NOAA)
- [x] Orion/Hercules - /apps/contrib/spack-stack/

SUMMARY:
- [x] Hera: /contrib/spack-stack/
- [x] Jet: /contrib/spack-stack/
- [x] Gaea5: /ncrc/proj/epic/spack-stack/
- [x] Gaea6: /ncrc/proj/epic/spack-stack/c6/
- [x] Orion: /apps/contrib/spack-stack/
- [x] Hercules: /apps/contrib/spack-stack/

**NOTE for Orion and Hercules!**
We have to login to one of two login nodes:
`orion-devel-1` or `orion-devel-2` (for Orion) and `hercules-devel-1` or `hercules-devel-2` (for Hercules)
You cannot ssh from role account. You first ssh as $USER and then sudo to role-epic.
Filesystems are separate, they are not shared between Orion and Hercules.

**Comment by climbfuji** [comment]
@RatkoVasic-NOAA @AlexanderRichert-NOAA Is this all done?

**Comment by RatkoVasic-NOAA** [comment]
Done only on Hera and Jet.
Tried on Gaea, but very quickly ran out of disk space - still using same directory.
Orion and Hercules - still using old directory.
I believe this issue can be closed.

**Comment by climbfuji** [comment]
Why closing the issue? Should we not keep it open until Orion, Hercules and Gaea are also using `/contrib`? Or do we expect that this won't happen at all?

**Comment by RatkoVasic-NOAA** [comment]
Gaea- no disk space. No need for /contrib, we use /ncrc.
I don't see Orion and Hercules directories for this.

**Comment by AlexanderRichert-NOAA** [comment]
On Gaea the equivalent space is /usw/spack-stack, see the PR description.

I'm not sure what happened on Orion/Hercules, it looks like the contrib space got relocated.

All of these systems should still be transitioned to using contrib space.

**Comment by RatkoVasic-NOAA** [comment]
@AlexanderRichert-NOAA , so /contrib existed on Orion and Hercules before, or it was under different name? I installed 1.8.0 on same space as before. Do you want to push for getting that space on MSU machines?

**Comment by AlexanderRichert-NOAA** [comment]
/apps/contrib/spack-stack/ is already there and owned by the role account.

**Comment by RatkoVasic-NOAA** [comment]
> /apps/contrib/spack-stack/ is already there and owned by the role account.

Ooops, I didn't know about these directories. I installed 1.8.0 on /work/noaa/epic/role-epic/spack-stack/ space. Should we start using new space from the next release?

BTW, just checked, we cannot write to that directories:
```
Orion:
[role-epic@Orion:/apps/contrib/spack-stack]$ touch test
touch: cannot touch 'test': Read-only file system
[role-epic@Orion:/apps/contrib/spack-stack]$ ll -d ../spack-stack
drwxr-xr-x 2 role-epic root 10 Jul 01 2024 09:58:39 ../spack-stack

Hercules:
[role-epic@Hercules:/apps/contrib/spack-stack]# touch test
touch: cannot touch 'test': Read-only file system
[role-epic@Hercules:/apps/contrib/spack-stack]# ll -d ../spack-stack
drwxr-xr-x 2 role-epic root 10 Jul 01 2024 09:57:54 ../spack-stack
```

**Comment by climbfuji** [comment]
My suggestion to be to move to `contrib` on the remaining systems with the next release / the next release candidates. spack-stack-1.9.0 is less than 3 months away!

**Comment by AlexanderRichert-NOAA** [comment]
This has been open since June, and we didn't go back and do previous releases in anticipation of the 1.8.0 release. Can we deploy 1.8.0 to these spaces?

**Comment by climbfuji** [comment]
As long as Ratko is ok doing the installs, and as long as somebody else than me (1) manages merging the updates into the release/1.8.0 branch, (2) makes sure the Wiki gets updated accordingly, (3) merges (cherry-picks) the updates that go into release/1.8.0 for develop, and (4) retags the release once this is all done, fine by me.

**Comment by RatkoVasic-NOAA** [comment]
They are already on Hera and Jet.
On Gaea we cannot use /usw/spack-stack/ (lack of disk space)
On Hercules and Orion, we cannot write to /apps/contrib/spack-stack/

So, basically, nothing that we can change.

**Comment by AlexanderRichert-NOAA** [comment]
If you are unable to write to the contrib space on Hercules and Orion, please reach out to the support desk. I don't know the story around disk space on Gaea, but it sounds like either space needs to be cleaned up or it will need intervention from the support desk.

**Comment by RatkoVasic-NOAA** [comment]
I can ask helpdesk for Orion/Hercules, but for Gaea - I don't think it is safe to use disk which is low on storage space.

**Comment by AlexanderRichert-NOAA** [comment]
So what's the plan for Gaea?

**Comment by RatkoVasic-NOAA** [comment]
I'm on Gaea right now. Creating BIG files to test how much is available over there. Last time I tried, it failed after ONLY 12GB (8GB c5 and 4 GB c6).
That is very small to play with.

**Comment by RatkoVasic-NOAA** [comment]
```
drwxr-xr-x 3 role.epic wpo        4096 Sep 11 2024 13:02:33 c5
-rw-r--r-- 1 role.epic wpo 13816074240 Oct 08 2024 11:54:00 c5.tar
drwxr-xr-x 3 role.epic wpo        4096 Sep 11 2024 13:02:35 c6
-rw-r--r-- 1 role.epic wpo 13203763200 Oct 08 2024 11:59:16 c6.tar
-rw-r--r-- 1 role.epic wpo  8208449536 Oct 08 2024 12:02:05 x-c5.tar
[role.epic@gaea53:/usw/spack-stack]# cp: error writing 'x-c5.tar': No space left on device
```
I added 27+8 GBs, and it ran out of space.  Last time it failed with much less - I couldn't install 2 spack-stacks (c5 and c6).
I'm not sure that we can trust this space. What do you think?

**Comment by AlexanderRichert-NOAA** [comment]
If there's enough room for two installations (each ue-intel is <10GB), then go ahead and install, and if you run out of space or run into other issues, reach out to the support desk ASAP.

**Comment by RatkoVasic-NOAA** [comment]
I can do that.
My concern is it is volatile, we don't know how much space we have. Today we have enough to install both c5 and c6. I'll do installations today.

**Comment by ulmononian** [comment]
@AlexanderRichert-NOAA @RatkoVasic-NOAA is there a reason why we cannot use `ncrc` on gaea c5/c6? if there is only enough space to maintain a few installations on `usw`, and this is not a consistent/guaranteed amount of space (i.e., last week there was 0GB available, today only 30GB), i do think there is a risk of setting the primary install location to be on `usw`.

**Comment by AlexanderRichert-NOAA** [comment]
Is it the same underlying filesystem? The idea was to try to use NFS rather than parallel filesystems on each machine, but if /usw is a parallel FS anyway then it probably doesn't matter.

**Comment by RatkoVasic-NOAA** [comment]
/usw is also on /ncrc, it is just symbolic link /usw -> /ncrc/usw

```
[role.epic@gaea53:/autofs]# df ncrc-svm1_proj ncrc-svm1_usw
Filesystem                     1K-blocks      Used  Available Use% Mounted on
ncrc-svm1.ncrc.gov:/ncrc/proj 2147483680 959388864 1188094816  45% /autofs/ncrc-svm1_proj
ncrc-svm1.ncrc.gov:/ncrc/usw    88080384  66469472   21610912  76% /autofs/ncrc-svm1_usw
```

**Comment by RatkoVasic-NOAA** [comment]
I just got answer rom MSU helpdesk.
We have to login to one of two login nodes:
`orion-devel-1` or `orion-devel-2` (for Orion) and `hercules-devel-1` or `hercules-devel-2` (for Hercules)
You cannot ssh from role account. You first ssh as $USER and then sudo to role-epic.
Filesystems are separate, they are not shared between Orion and Hercules.
If we go forward with this disk, we have to add it to documentation ([orion](https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html#msu-orion), [hercules](https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html#msu-hercules)).
I'll go ahead and install 1.8.0 there.

**Comment by RatkoVasic-NOAA** [comment]
Let's summarize here:

**Comment by RatkoVasic-NOAA** [comment]
@AlexanderRichert-NOAA , issue is updated in header. You can close ticket.
