### ISSUE TITLE
[INSTALL]: BUFR 12.1.0

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [JCSDA/spack-stack#1194]
### Package name

BUFR

### Package version/tag

12.1.0

### Build options

Python-enabled, otherwise standard options

### Installation timeframe

A test installation on Hera and Orion, then included in the next spack-stack release.

### Other information

The tag was released yesterday (https://github.com/NOAA-EMC/NCEPLIBS-bufr/tree/v12.1.0).

Orion has had issues with bufr 11.7.0 since upgrading to Rocky 9.  It would be nice to test this version out to see if it is any better. https://github.com/JCSDA/spack-stack/issues/1166

### WCOSS2

- [X] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: General questions

Package manager: @jbathegit
URL: https://github.com/NOAA-EMC/NCEPLIBS-bufr/tree/v12.1.0
Upgraded version
License: https://github.com/NOAA-EMC/NCEPLIBS-bufr/blob/v12.1.0/LICENSE.md
Justification: The GSI needs this version to use the latest BUFR upgrades and to include optimizations that produced a slowdown in versions 12.0 and 12.0.1.
Dependencies: Intel compiler, Python, numpy, cmake

### WCOSS2: Installation and testing

@jbathegit, could you fill in this section?

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [X] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [X] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [X] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [X] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [X] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [X] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [X] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [X] There is sufficient documentation to support maintenance
- [X] There are no known security vulnerabilities or weaknesses
- [X] Installing and running the code does not require privileged processes/users
- [X] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [X] There are no concerns related to SA, SI, and SC NIST control families

**Comment by DavidHuber-NOAA** [comment]
FYI @russtreadon-noaa, @aerorahul, @jbathegit.

**Comment by RussTreadon-NOAA** [comment]
Tagging @CoryMartin-NOAA.  Should we update GDASApp to `bufr/12.1.0`?

**Comment by climbfuji** [comment]
Duplicate of #1060
