### ISSUE TITLE
To resolve after release/1.5.1: Python variant +ssl issues on systems with old openssl/openssh

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#854]
**Describe the bug**
This is a slightly complicated problem (to describe and even more to solve).

On systems with older `libssh` and `libssl`, we need to turn of the `+ssl` variant for Python to avoid (a) build errors for certain packages (e.g. `fckit`) and concretization issues (duplicate packages). The problem seems to be that none of the packages in our stack explicitly depends on `libssh` and that not all software correctly defines its dependencies on it.

For example, building `fckit` with a newer version of `openssl` than installed in the OS leads to an error in the linker step, originating from `libssh`, that certain `openssl` symbols (from the older `libssl` installation in the OS) are not found.

Python 3.10 apparently requires newer `openssl` versions for enabling its `+ssl` variant, therefore we can't have that option turned on for certain systems.

The workaround for release/1.5.1 was to turn off the `ssl` variant in the respective site configs (see https://github.com/JCSDA/spack-stack/pull/853).

**To Reproduce**
See above

**Expected behavior**
Hidden dependency on `openssh` package (`libssh`) identified and added to package recipe, so that both `openssl` and `openssh` are installed by spack if necessary and the `ssl` variant for Python can be turned back on.

**System:**
Errors seen on Derecho, Gaea C5, Narwhal so far

**Additional context**
n/a

**Comment by climbfuji** [comment]
My suspicion is that it has to do with using an external cmake or not ... to be confirmed.

**Comment by climbfuji** [comment]
See https://github.com/JCSDA/spack-stack/issues/863 for the explanation. I think the correct behavior in this case would be that spack has to refuse using a external/OS curl when `openssl` is built by spack-stack. @AlexanderRichert-NOAA FYI

**Comment by climbfuji** [comment]
I verified on Narwhal that the following works: remove external `curl`, `openssh` and `openssl`. No need to specify a `~ssl` variant for Python. We need to make this change for all site configs before release/1.6.0 (mark as completed if no changes needed or if changed and tested correctly:
- [x] acorn (no changes needed)
- [x] aws-pcluster (built successfully)
- [x] casper (built successfully)
- [x] cheyenne (removed)
- [x] derecho (built successfully)
- [x] discover (built successfully)
- [x] emc-rhel (built successfully)
- [x] frontera (removed)
- [x] gaea-c4 (removed)
- [x] gaea-c5 (built successfully)
- [x] hera (built successfully)
- [x] hercules (built successfully)
- [x] jet (needs testing)
- [x] linux.default (no changes needed)
- [x] macos.default (no changes needed)
- [x] narwhal
- [x] nautilus (built successfully)
- [x] noaa-aws (deferred to https://github.com/JCSDA-internal/jedi-tools/issues/325)
- [x] noaa-azure (deferred to https://github.com/JCSDA-internal/jedi-tools/issues/325)
- [x] noaa-gcloud (deferred to https://github.com/JCSDA-internal/jedi-tools/issues/325)
- [x] orion (built successfully)
- [x] s4 (built successfully)
