### ISSUE TITLE
[INSTALL]: fms@2023.03 in spack-stack-1.5.1 and develop

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#860]
### Package name

fms

### Package version/tag

2023.03

### Build options

current

### Installation timeframe

There is a bug in fms@2023.02.01 that leads to a crash with the GNU compilers, see https://github.com/ufs-community/ufs-weather-model/pull/1147#issuecomment-1791298098.

We need to add fms@2023.03 in develop and then go back and install it in spack-stack 1.5.1 (post release).

### Other information

PRs for release/1.5.1 branches (will be merged back to develop afterwards):
- [x] https://github.com/JCSDA/spack/pull/363
- [x] https://github.com/JCSDA/spack-stack/pull/855/files

List of platforms:
- [x] Hercules (@climbfuji) - directly in `unified-env` as part of the roll out (changes to be committed to release branch)
- [x] Orion (@ulmononian)
- [x] Discover (@climbfuji)
- [x] Casper (@climbfuji)
- [x] Derecho (EPIC)
- [x] Acorn (EMC)
- [x] Gaea C4 (EMC)
- [x] Gaea C5 (@RatkoVasic-NOAA )
- [x] Hera (@RatkoVasic-NOAA )
- [x] Jet @RatkoVasic-NOAA )
- [x] Narwhal (@climbfuji)
- [x] Nautilus (@climbfuji)
- [x] S4 (@climbfuji)
- [x] Parallel Works (JCSDA installations; @climbfuji) - deferred to when clusters are started again, see:
    - [x] AWS --> https://github.com/JCSDA-internal/jedi-tools/issues/325
    - [x] Azure --> https://github.com/JCSDA-internal/jedi-tools/issues/325
    - [x] Gcloud --> https://github.com/JCSDA-internal/jedi-tools/issues/325
- [ ] Parallel Works (EPIC installations)
    - [ ] AWS
    - [ ] Azure
    - [ ] Gcloud
- [x] AWS ParallelCluster (@climbfuji)
- [x] AWS Single-node AMI (@climbfuji)
- [ ] ~~JEDI CI containers~~ (for now these still have `fms@release-jcsda`)

### WCOSS2

- [ ] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

**Comment by climbfuji** [comment]
We have the go ahead for this installation, so let's make sure we get it on the systems. @natalie-perlin @RatkoVasic-NOAA @ulmononian @AlexanderRichert-NOAA does the suggest splitting of the systems work for you?

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA @ulmononian I've completed the "JCSDA assignment", and Alex the "EMC assignment". Can EPIC please do the remaining platforms and then create the ufs-weather-model PR that updates to spack-stack-1.5.1 with esmf@8.5.0, mapl@2.40.3, fms@2023.03? @jkbk2004 FYI

**Comment by RatkoVasic-NOAA** [comment]
I'll work on this on the most platforms. I'm not sure who is going to do it on NOAA cloud.

**Comment by RatkoVasic-NOAA** [comment]
> @AlexanderRichert-NOAA @ulmononian I've completed the "JCSDA assignment", and Alex the "EMC assignment". Can EPIC please do the remaining platforms and then create the ufs-weather-model PR that updates to spack-stack-1.5.1 with esmf@8.5.0, mapl@2.40.3, fms@2023.03? @jkbk2004 FYI

@climbfuji I got instructions for adding fms@2023.03.
What is deal with esmf@8.5.0 and mapl@2.40.3?

**Comment by climbfuji** [comment]
Nothing needs to be done for esmf and mapl they are already installed

**Comment by ulmononian** [comment]
@climbfuji @RatkoVasic-NOAA @natalie-perlin orion, jet, hera, gaea c5 are done (thanks @RatkoVasic-NOAA for doing hera/jet/gaea c5). 

on derecho, fms w/ intel installed successfully, but there was an issue with the gcc version (see attached). i will be out most of next week, so if someone could please take a look at this, it would be very helpful. the log is at `/glade/work/epicufsrt/contrib/spack-stack/derecho/spack-stack-1.5.1/log.install.unified-env.003.fms-2023p03.gcc`.

![Screen Shot 2023-11-17 at 5 07 42 PM](https://github.com/JCSDA/spack-stack/assets/43379611/2c34806f-246f-4549-a05f-a7b95c0ade5a)

**Comment by climbfuji** [comment]
> @climbfuji @RatkoVasic-NOAA @natalie-perlin orion, jet, hera, gaea c5 are done (thanks @RatkoVasic-NOAA for doing hera/jet/gaea c5).
> 
> on derecho, fms w/ intel installed successfully, but there was an issue with the gcc version (see attached). i will be out most of next week, so if someone could please take a look at this, it would be very helpful. the log is at `/glade/work/epicufsrt/contrib/spack-stack/derecho/spack-stack-1.5.1/log.install.unified-env.003.fms-2023p03.gcc`.
> 
> ![Screen Shot 2023-11-17 at 5 07 42 PM](https://user-images.githubusercontent.com/43379611/284009282-2c34806f-246f-4549-a05f-a7b95c0ade5a.png)

This requires a bug fix in FMS. I submitted a PR to the FMS repo for this and manually modified the 2023.03 code to install on Derecho with gcc.

**Comment by ulmononian** [comment]
spack-stack/1.5.1 has been installed on gcp and aws by @natalie-perlin. there was an issue with the azure cluster so that installation is not yet completed. we will add fms/2023.03 there once resolved.

**Comment by climbfuji** [comment]
> spack-stack/1.5.1 has been installed on gcp and aws by @natalie-perlin. there was an issue with the azure cluster so that installation is not yet completed. we will add fms/2023.03 there once resolved.

Note that I didn't have any issues installing on azure, so please try using the site config from the final spack-stack-1.5.1 tag as is.

**Comment by climbfuji** [comment]
Either way I am going to close this since fms 2023.03 is either there or will be added once the Parallel Works systems are running again.
