### ISSUE TITLE
[INSTALL]: cprnc

### ISSUE THREAD

**Issue by jedwards4b** [JCSDA/spack-stack#885]
### Package name

cprnc

### Package version/tag

1.0.1

### Build options

needs netcdf-fortran

### Installation timeframe

please install on all supported hpc platforms

### Other information

This netcdf file comparison tool was distributed with cime, since cime was removed from the UFS project it has not been available.   Recently I created a [separate cprnc repository](https://github.com/ESMCI/cprnc).  And have created a [spack package ](https://github.com/spack/spack/pull/41237)for it as well.   Please consider merging this into JCSDA/spack and making it available on all platforms you support. 

### WCOSS2

- [ ] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: General questions

https://github.com/ESMCI/cprnc 

dependancies: netcdf-fortran

### WCOSS2: Installation and testing

Installed via spack - a set of unit tests is provided which run in the spack install step.

### WCOSS2: Technical & security review list

- [X] The code is mature, stable, and production ready
- [X] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [X] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [X] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [X] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [X] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [X] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [X] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [X] There is sufficient documentation to support maintenance
- [X] There are no known security vulnerabilities or weaknesses
- [X] Installing and running the code does not require privileged processes/users
- [X] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [X] There are no concerns related to SA, SI, and SC NIST control families

**Comment by AlexanderRichert-NOAA** [comment]
Is this needed for a particular application? If not, then for now I might lean toward merging the recipe into JCSDA Spack so that users who want it can easily install it on the HPC platforms on top of the spack-stack releases.

On a note of personal curiosity, how does this compare with, say, nccmp?

**Comment by jedwards4b** [comment]
It is a tool which is used to compare netcdf output of weather and climate models.  I had never heard of nccmp until now, I must admit that it seems like a similar tool.   I thought that this was the process to merge the recipe into JCSDA spack, that was my intent - please point me in the right direction if that is not the case.

**Comment by DeniseWorthen** [comment]
@AlexanderRichert-NOAA My two cents is that nccmp requires multiple flags to do the same thing (eg, we use in the RT system `` nccmp -d -S -q -f -g -B --Attribute=checksum --warn=format``, whereas ``cprnc`` does the same job w/ no flag (only the -m is required if you have a time dimension) and also detects differences in fields (present/absent) as well as reporting the exact i,j location of a field differnce as well as how different the fields are relative to their magnitude.

``cprnc`` is my go-to tool for diagnosing coupling issues, for example restart reproducibility or which field is no longer reproducing in a PR (I was able to use it last week to identify the exact first non-reproducing point for a large MOM6 PR). It would be very useful to have this available on any RDHPCS platform. If that means "merging the recipe so that users who want it can easily install it", then that would probably sufficient for my purposes, although at the pace we update spack-stack, I worry about how many times I, as a user, would be required to re-install it.

**Comment by climbfuji** [comment]
How about we make it part of the `ufs-weather-model-env` virtual package, this way it gets installed automatically in the unified environment and any other environment that uses `ufs-weather-model-env`? It would then be rolled out in the week before Christmas as part of spack-stack-1.6.0.

**Comment by DeniseWorthen** [comment]
@climbfuji It sounds like that would be the right course. Thanks.

**Comment by climbfuji** [comment]
Done: `spack-stack@1.6.0` is installed on all platforms (release will be announced tomorrow) and comes with `cprnc@1.0.3`
